# Generated by Django 6.0.2 on 2026-07-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='xer_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
