# Generated by Django 6.0.2 on 2026-08-03 05:02

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_xer_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=api.utils.project_image_file_path),
        ),
    ]
